apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springbootapp
  name: springbootapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: springbootapp
  template:
    metadata:
      labels:
        app: springbootapp
    spec:
      containers:
      - name: my-springbootapp
        image: zouhair1234/springbootapp
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springbootapp
    k8s-app: springbootapp
  name: springbootapp
spec:
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 9090
  type: LoadBalancer
  selector:
    app: springbootapp
